# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: 'Default'
  demands:
   - agent.name -equals DESKTOP-GSPVN3D-Win11
   - agent.version -equals 2.206.1

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar Cloud'
    organization: 'behl1anmol'
    scannerMode: 'MSBuild'
    projectKey: 'behl1anmol_Planner'
    projectName: 'Planner'
- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: dependency-check-build-task@6
  inputs:
    projectName: 'NetForce'
    scanPath: '$(Build.SourcesDirectory)/NetForce'
    format: 'HTML'
